# Generated by Django 5.2 on 2025-09-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('keywords', models.CharField(max_length=300)),
                ('additional_content', models.TextField(blank=True, help_text='Additional SEO content')),
                ('schema_markup', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='calculator',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Detailed description for SEO'),
        ),
        migrations.AddField(
            model_name='calculator',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show on homepage as featured'),
        ),
        migrations.AddField(
            model_name='calculator',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='calculator',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_section',
            field=models.TextField(blank=True, help_text='About section content'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='features_title',
            field=models.CharField(default='Why Choose Our Calculators?', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_statistics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_testimonials',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CalculatorField',
        ),
    ]
